version: "3.7"

services:
  db:
    image: 'mongo:latest'
    volumes:
      - 'mongo-vol:/data/db'
    networks:
      - cockpit

  cms:
    build: 'docker/cockpit'
    environment:
      COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: salty
      COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
      COCKPIT_DATABASE_NAME: cockpit_master
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - cockpit
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html/addons


networks:
  cockpit:
    driver: bridge

volumes:
  mongo-vol: null