version: '3.3'

services:
  cms:
    image: agentejo/cockpit
    ports:
      - 8080:80
    networks:
      - cockpit
    volumes:
         - ./Pipelines:/var/www/html/addons/Pipelines
         - ./pipelines.json:/var/www/html/storage/pipelines.json
         - ./Docker/cockpit/config.php:/var/www/html/config/config.php

networks:
  cockpit:
    driver: bridge